name: speech-banrep
channels:
- anaconda-fusion
- defaults
dependencies:
- appnope=0.1.0=py36_0
- bleach=1.5.0=py36_0
- bokeh=0.12.5=py36_0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- html5lib=0.999=py36_0
- icu=54.1=0
- ipykernel=4.6.1=py36_0
- ipython=6.0.0=py36_1
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jedi=0.10.2=py36_2
- jinja2=2.9.6=py36_0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.0.1=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- markupsafe=0.23=py36_2
- mistune=0.7.4=py36_0
- mkl=2017.0.1=0
- nbconvert=5.1.1=py36_0
- nbformat=4.3.0=py36_0
- notebook=5.0.0=py36_0
- numpy=1.12.1=py36_0
- openssl=1.0.2k=2
- pandas=0.20.1=np112py36_0
- pandocfilters=1.4.1=py36_0
- path.py=10.3.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pyyaml=3.12=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=1
- qtconsole=4.3.0=py36_0
- readline=6.2=2
- requests=2.14.2=py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.18=0
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - appdirs==1.4.3
  - asn1crypto==0.22.0
  - cachetools==2.0.0
  - cffi==1.10.0
  - cryptography==1.8.1
  - dill==0.2.6
  - enum34==1.1.6
  - future==0.16.0
  - gapic-google-cloud-datastore-v1==0.15.3
  - gapic-google-cloud-error-reporting-v1beta1==0.15.3
  - gapic-google-cloud-logging-v2==0.91.3
  - gapic-google-cloud-pubsub-v1==0.15.4
  - gapic-google-cloud-spanner-admin-database-v1==0.15.3
  - gapic-google-cloud-spanner-admin-instance-v1==0.15.3
  - gapic-google-cloud-spanner-v1==0.15.3
  - gapic-google-cloud-speech-v1==0.15.3
  - gapic-google-cloud-speech-v1beta1==0.15.3
  - gapic-google-cloud-vision-v1==0.90.3
  - google-api-python-client==1.6.2
  - google-auth==1.0.1
  - google-auth-httplib2==0.0.2
  - google-cloud==0.25.0
  - google-cloud-bigquery==0.24.0
  - google-cloud-bigtable==0.24.0
  - google-cloud-core==0.24.1
  - google-cloud-datastore==1.0.0
  - google-cloud-dns==0.24.0
  - google-cloud-error-reporting==0.24.2
  - google-cloud-language==0.24.1
  - google-cloud-logging==1.0.0
  - google-cloud-monitoring==0.24.0
  - google-cloud-pubsub==0.25.0
  - google-cloud-resource-manager==0.24.0
  - google-cloud-runtimeconfig==0.24.0
  - google-cloud-spanner==0.24.2
  - google-cloud-speech==0.24.0
  - google-cloud-storage==1.1.1
  - google-cloud-translate==0.24.0
  - google-cloud-vision==0.24.0
  - google-gax==0.15.13
  - google-resumable-media==0.0.2
  - googleapis-common-protos==1.5.2
  - grpc-google-iam-v1==0.11.1
  - grpcio==1.3.5
  - httplib2==0.10.3
  - idna==2.5
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - oauth2client==3.0.0
  - packaging==16.8
  - ply==3.8
  - prompt-toolkit==1.0.14
  - proto-google-cloud-datastore-v1==0.90.4
  - proto-google-cloud-error-reporting-v1beta1==0.15.3
  - proto-google-cloud-logging-v2==0.91.3
  - proto-google-cloud-pubsub-v1==0.15.4
  - proto-google-cloud-spanner-admin-database-v1==0.15.3
  - proto-google-cloud-spanner-admin-instance-v1==0.15.3
  - proto-google-cloud-spanner-v1==0.15.3
  - proto-google-cloud-speech-v1==0.15.3
  - proto-google-cloud-speech-v1beta1==0.15.3
  - proto-google-cloud-vision-v1==0.90.3
  - protobuf==3.3.0
  - pyasn1==0.2.3
  - pyasn1-modules==0.0.8
  - pycparser==2.17
  - pydub==0.19.0
  - pyopenssl==17.0.0
  - pyparsing==2.2.0
  - pysolr==3.6.0
  - rsa==3.4.2
  - speechrecognition==3.6.5
  - uritemplate==3.0.0
  - watson-developer-cloud==0.26.0

